import Head from 'next/head'
import React, { useState } from 'react'

export default function Home() {
  const [data, setData] = useState({
    loading: true,
    data: null,
  })

  const onSubmit = () => {
    fetch('/login')
      .then((res) => res.json)
      .then((data) => setData({ loading: false, data }))
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={onSubmit}>
          <input type="text" placeholder="Name" />
          <input type="text" placeholder="Name" />
          <button type="submit">Login</button>
        </form>
        {data.data}
      </main>
    </>
  )
}
